config/routes.rb
SampleApp::Application.routes.draw do

  resources :messages

  resources :receivers

   resources :users do
    member do
    end
  end

  
  resources :sessions,      :only => [:new, :create, :destroy] do
    collection do
      get :forgot_password, :new_password, :update_reset_password
      post :send_reset_password, :reset_new_password
    end
  end
  resources :comments,    :only => [:create, :destroy, :new, :show]
  
 root :to => "pages#home"

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/home', :to => 'pages#home'
   match '/sendtext', :to => 'pages#sendtext'
   match '/save_receiver_data', :to => 'pages#save_receiver_data'

 

end

app/models/receiver.rb
class Receiver < ActiveRecord::Base
  has_and_belongs_to_many :messages
  validates :phone_number,  :presence => true
  validates :name,  :presence => true
  validates :breakfast_time, :lunch_time, :snack_time, :dinner_time, :presence => true
end

app/controllers/receivers_controller.rb
class ReceiversController < ApplicationController
  # GET /receivers
  # GET /receivers.xml
  def index
    @receivers = Receiver.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @receivers }
    end
  end

  # GET /receivers/1
  # GET /receivers/1.xml
  def show
    @receiver = Receiver.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @receiver }
    end
  end

  # GET /receivers/new
  # GET /receivers/new.xml
  def new
    @receiver = Receiver.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @receiver }
    end
  end

  # GET /receivers/1/edit
  def edit
    @receiver = Receiver.find(params[:id])
  end

  # POST /receivers
  # POST /receivers.xml
  def create
    @receiver = Receiver.new(params[:receiver])

    respond_to do |format|
      if @receiver.save
        format.html { redirect_to(@receiver, :notice => 'Receiver was successfully created.') }
        format.xml  { render :xml => @receiver, :status => :created, :location => @receiver }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @receiver.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /receivers/1
  # PUT /receivers/1.xml
  def update
    @receiver = Receiver.find(params[:id])

    respond_to do |format|
      if @receiver.update_attributes(params[:receiver])
        format.html { redirect_to(@receiver, :notice => 'Receiver was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @receiver.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /receivers/1
  # DELETE /receivers/1.xml
  def destroy
    @receiver = Receiver.find(params[:id])
    @receiver.destroy

    respond_to do |format|
      format.html { redirect_to(receivers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/receivers_helper.rb
module ReceiversHelper
end

app/views/receivers/_form.html.erb
<%= form_for(@receiver) do |f| %>
  <% if @receiver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@receiver.errors.count, "error") %> prohibited this receiver from being saved:</h2>

      <ul>
      <% @receiver.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/receivers/edit.html.erb
<h1>Editing receiver</h1>

<%= render 'form' %>

<%= link_to 'Show', @receiver %> |
<%= link_to 'Back', receivers_path %>

app/views/receivers/index.html.erb
<h1>Listing receivers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Phone number</th>
    <th>Description</th>
    <th>Email</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @receivers.each do |receiver| %>
  <tr>
    <td><%= receiver.name %></td>
    <td><%= receiver.phone_number %></td>
    <td><%= receiver.description %></td>
    <td><%= receiver.email %></td>
    <td><%= receiver.status %></td>
    <td><%= link_to 'Show', receiver %></td>
    <td><%= link_to 'Edit', edit_receiver_path(receiver) %></td>
    <td><%= link_to 'Destroy', receiver, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Receiver', new_receiver_path %>

app/views/receivers/new.html.erb
<h1>New receiver</h1>

<%= render 'form' %>

<%= link_to 'Back', receivers_path %>

app/views/receivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @receiver.name %>
</p>

<p>
  <b>Phone number:</b>
  <%= @receiver.phone_number %>
</p>

<p>
  <b>Description:</b>
  <%= @receiver.description %>
</p>

<p>
  <b>Email:</b>
  <%= @receiver.email %>
</p>

<p>
  <b>Status:</b>
  <%= @receiver.status %>
</p>


<%= link_to 'Edit', edit_receiver_path(@receiver) %> |
<%= link_to 'Back', receivers_path %>