config/routes.rb
SampleApp::Application.routes.draw do

  resources :messages

  resources :receivers

   resources :users do
    member do
    end
  end

  
  resources :sessions,      :only => [:new, :create, :destroy] do
    collection do
      get :forgot_password, :new_password, :update_reset_password
      post :send_reset_password, :reset_new_password
    end
  end
  resources :comments,    :only => [:create, :destroy, :new, :show]
  
 root :to => "pages#home"

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/home', :to => 'pages#home'
   match '/sendtext', :to => 'pages#sendtext'
   match '/save_receiver_data', :to => 'pages#save_receiver_data'

 

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul id="nav">
      <li>@copyright 2011</li>
      <li>&nbsp&nbsp</li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
  <head>
  <div class="round" style="margin-top:2px;background-color: #eeeeee;float:right;width:100%;height:2px;">
    <% if signed_in? %>
      <span style="float:right;margin-right:10px;margin-top:40px;">
        Welcome <%=current_user.email%>&nbsp;|&nbsp;<%= link_to "Sign out", signout_path %>
      </span>
    <% end %>
  </div>
</head>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]--><%= stylesheet_link_tag "default" %>
    <%= stylesheet_link_tag 'south-street/jquery-ui-1.8.4.custom' %>
    <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Cabin:bold' %>
     <%= javascript_include_tag 'application' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <meta name="description" content="Text 2 Weightloss.com enables you to loose weight by letting you or your loved ones send automatic text messages number of times a day. Loose weight with help of your loved ones weight loss" />
    <meta name="keywords" content="weight loss, loved ones send text messages daily, weight loss diet, diet, weight loss, diet plan, weightloss, dieting, weight loss program, healthy diet, diet program, weight loss plans, healthy weight loss, healthy dieting" />
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-7483197-3']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
  </head>
  <body>
    <%= link_to image_tag("t2wl_logo_words.gif",:style =>"width:100%;", :alt =>"milkeggs"), root_path %>
    <%= link_to image_tag("t2wl_logo.gif",:style =>"width:100%;", :alt =>"milkeggs"), root_path %>
    <div id="container" class="container_12">
      <ul id="nav">
        <p>
           <%= render 'layouts/header' %>
        <li><%= link_to "Users", users_path %></li>
        <% if signed_in? %>
          <% if false%>
            <li><%= link_to "Retirees", retiree_path %></li>
            <li> <%= link_to "Profile", current_user %> </li>
            <li><%= link_to "Users", users_path %></li>
            <li><%=link_to "Moderate Comments", comments_path  if current_user.admin? %></li>
          <% end %>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
        <% end %>
        </p>
      </ul>
    </nav>
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    <div class="grid_12">
      <%= render 'layouts/footer' %>
    </div>
    <br />
    <br />
    <%= debug(params) if Rails.env.development? %>
  </div> <!-- container -->
</body>
</html>